# Generated by Django 4.0.6 on 2022-07-22 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='basvuru',
            name='momname',
            field=models.CharField(default='girilmedi', max_length=30),
        ),
        migrations.AlterField(
            model_name='basvuru',
            name='surname',
            field=models.CharField(default='girilmedi', max_length=30),
        ),
    ]
